pipeline:
  identifier: Build_test002_1699355146400
  name: Build test002
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: test002
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Bash
                    command: |-
                      echo "Building..."
                      sleep 10
                      echo "Build Complete!"
              - step:
                  type: Run
                  name: Test
                  identifier: Test
                  spec:
                    shell: Bash
                    command: |-
                      echo "Testing..."
                      sleep 10
                      echo "Tests Complete!"
              - step:
                  type: Run
                  name: Deploy
                  identifier: Deploy
                  spec:
                    shell: Bash
                    command: |-
                      echo "Deploying ..."
                      sleep 10
                      echo "Deploy Complete!"
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
