pipeline:
  identifier: Build_test002_1699355146400
  name: Build test002
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Bash
                    command: |-
                      echo "Building..."
                      sleep 10
                      echo "Build Complete!"
              - parallel:
                  - step:
                      type: Run
                      name: Test1
                      identifier: Test
                      spec:
                        shell: Bash
                        command: |-
                          echo "Running Test1..."
                          sleep 10
                          echo "Test1 testing Complete!"
                  - step:
                      type: Run
                      name: Test2
                      identifier: Test2
                      spec:
                        shell: Bash
                        command: |-
                          echo "Running Test2 ..."
                          sleep 10
                          echo "Test2 testing complete!"
              - step:
                  type: Run
                  name: Deploy
                  identifier: Deploy
                  spec:
                    shell: Bash
                    command: |-
                      echo "Deploying ..."
                      sleep 10
                      echo "Deploy Complete!"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
        type: CI
        description: ""
