name: test-and-build-image2
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    env:
      VUE_APP_ROLLOUT_KEY: ${{ secrets.VUE_APP_ROLLOUT_KEY }}
    steps:
      - uses: actions/checkout@v4
